
export const UPDATE_SPIKE_IMAGE_URL = 'UPDATE_SPIKE_IMAGE_URL'
export const UPDATE_OTHERAPP_IMAGE_URL = 'UPDATE_OTHERAPP_IMAGE_URL'
export const UPDATE_MORE_IMAGE_URL = 'UPDATE_MORE_IMAGE_URL'
export const UPDATE_LIKE_IMAGE_URL = 'UPDATE_LIKE_IMAGE_URL'
export const UPDATE_HEADER_IMAGE_URL = 'UPDATE_HEADER_IMAGE_URL'
export const INCREASE_SPIKE_ONE_SECOND = 'INCREASE_SPIKE_ONE_SECOND'




